services:
    next:
        image: "ghcr.io/challenge-chu/backend/next-app:dev"
        ports:
            - "80:3000"
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - NEXTAUTH_URL=${NEXTAUTH_URL}
            - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
            - ADMIN_USERNAME=${ADMIN_USERNAME}
            - ADMIN_PASSWORD=${ADMIN_PASSWORD}
            - JWT_SECRET=${JWT_SECRET}
        labels:
            - "com.centurylinklabs.watchtower.enable=true"
        networks:
            - app-network
        depends_on:
            - postgres

    postgres:
        image: "postgres:16"
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
            - TZ=Europe/Paris
            - PGTZ=Europe/Paris
        volumes:
            - ./postgres:/var/lib/postgresql/data
        networks:
            - app-network

networks:
    app-network:
        driver: bridge