services:
    next:
        build:
            context: .
            target: next
        ports:
            - "3000:3000"
        command: ["npm", "run", "dev"]
        volumes:
            - ".:/app/"
    postgres:
        image: "postgres:16"
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        volumes:
            - ./postgres:/var/lib/postgresql/data
            
