import { Inter } from "next/font/google";
import "../globals.css";
import { Theme } from "react-daisyui";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" data-theme="mytheme">
            <body className={inter.className + " bg-primary"}>
                <p>LAYOUT FULL</p>

                {children}
            </body>
        </html>
    );
}
