import { Inter } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" data-theme="mytheme">
            <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
            />

            <body
                className={inter.className + " flex flex-nowrap min-h-screen"}
            >
                <Sidebar />
                <main className="flex-1 p-10 bg-base-100">{children}</main>
            </body>
        </html>
    );
}
