import { Inter } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/Sidebar/Sidebar";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" data-theme="mytheme">
            <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
            />

            <body
                className={
                    inter.className +
                    " flex flex-col lg:flex-row lg:flex-nowrap min-h-screen"
                }
            >
                <Sidebar />
                <main className="flex-1 p-4 lg:p-10 bg-base-100">
                    {children}
                </main>
                <Toaster className="toast" position="top-right" />
            </body>
        </html>
    );
}
