import { Inter } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/Sidebar/Sidebar";
import { Toaster } from "react-hot-toast";
import { getServerSession } from "next-auth";
import authOptions from "@/utils/authOptions";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const session = await getServerSession(authOptions);
    console.log("SESSION CONNECTEE");
    console.log(session);
    return (
        <html lang="en" data-theme="mytheme">
            <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
            />

            <body
                className={
                    inter.className +
                    " flex flex-col lg:flex-row lg:flex-nowrap min-h-screen"
                }
            >
                <Sidebar />
                <main className="flex-1 p-4 lg:p-10 bg-base-100">
                    {children}
                </main>
                <Toaster
                    containerStyle={{
                        zIndex: "99999 !important",
                    }}
                    toastOptions={{
                        className: "react-hot-toast",
                        style: {
                            zIndex: "99999 !important",
                        },
                    }}
                    className="toast"
                    position="top-center"
                />
            </body>
        </html>
    );
}
